[nv_codec_headers]
git-tree-sha1 = "b269309b2ffb147c00dd1a2ad74c7beeac1941e9"

    [[nv_codec_headers.download]]
    sha256 = "c6841432e4e07ea4a22385a9f54311b8e5fcff36a793371b033cdf2bc39fb21c"
    url = "https://github.com/JuliaBinaryWrappers/nv_codec_headers_jll.jl/releases/download/nv_codec_headers-v10.0.26+1/nv_codec_headers.v10.0.26.any.tar.gz"
